---
- name: Configurar proxy APT de jumpstart en backends UTM
  hosts: backends:backend
  become: yes

  tasks:
    - name: Configurar proxy APT usando jumpstart
      copy:
        dest: /etc/apt/apt.conf.d/01proxy
        content: |
          Acquire::http::Proxy "http://10.10.10.1:3142";
          Acquire::https::Proxy "false";
        owner: root
        group: root
        mode: "0644"

    - name: Probar actualización de caché APT
      apt:
        update_cache: yes
