[frontends]
frontend1 ansible_host=10.0.0.10
frontend2 ansible_host=10.0.0.11

[backends]
backend1 ansible_host=10.10.10.20
backend2 ansible_host=10.10.10.21

[infra]
balanceador ansible_host=10.0.0.1
router-linux ansible_host=10.0.0.254

[zabbix_server]
backend1 ansible_host=10.10.10.20

[zabbix_agent_nodes]
frontend1 ansible_host=10.0.0.10
frontend2 ansible_host=10.0.0.11
backend2 ansible_host=10.10.10.21
balanceador ansible_host=10.0.0.1
router-linux ansible_host=10.0.0.254

[all:vars]
ansible_user=alejandroro
ansible_ssh_private_key_file=/home/alejandroro/.ssh/id_ed25519
ansible_python_interpreter=/usr/bin/python3
