- hosts: backends
  become: yes

  tasks:
    - name: Instalar NGINX
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Crear página identificativa en backend1
      copy:
        dest: /var/www/html/index.html
        content: "SOY BACKEND1\n"
        owner: www-data
        group: www-data
        mode: "0644"
      when: inventory_hostname == "10.10.10.20"

    - name: Crear página identificativa en backend2
      copy:
        dest: /var/www/html/index.html
        content: "SOY BACKEND2\n"
        owner: www-data
        group: www-data
        mode: "0644"
      when: inventory_hostname == "10.10.10.21"

    - name: Reiniciar y activar NGINX
      systemd:
        name: nginx
        state: restarted
        enabled: yes
